import type { Metadata } from "next";
import "../styles/globals.css";
import { cn } from "@/lib/utils";
import { 
  geistSans, 
  geistMono, 
  space,
  playfair
} from "@/styles/fonts";
import { Noto_Sans, Playfair_Display } from "next/font/google";

const playfairDisplayHeading = Playfair_Display({subsets:['latin'],variable:'--font-heading'});

const notoSans = Noto_Sans({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning className={cn("font-sans", notoSans.variable, playfairDisplayHeading.variable)}>
      <body className={cn("min-h-full flex flex-col",
        geistSans.variable, geistMono.variable, playfair.variable, space.variable
      )}>
        {children}
      </body>
    </html>
  );
}
